### ISSUE TITLE
matrixCity street problem

### ISSUE THREAD

**Issue by XiaokangWei** [city-super/Octree-GS#16]
Hi， Great job! Thanks for release code.  i try to run this method on matrixCtiy street scene and use you provided init_point_cloud.ply,  but i cannot get a good performance result. like these example:

![00007](https://github.com/city-super/Octree-GS/assets/159465749/13ac6ec9-9f9b-483c-9d58-8e3f513e077a)
![00020](https://github.com/city-super/Octree-GS/assets/159465749/bc351c06-f88d-4724-80fe-1a71629af303)
![00033](https://github.com/city-super/Octree-GS/assets/159465749/c9895067-06ee-4ad4-9b83-d1eed2a155d1)

so could you help me check where is the error?

Thanks!

**Comment by jianglh-WHU** [comment]
Hi~ There are two possible reasons:
1. we release the ply file which is used for the aerial images of the small city dataset. If you want to use the street images, I recommend fusing the RGBD images into a point cloud. You can use this script: https://github.com/city-super/MatrixCity/blob/main/scripts/rgbd2pc.py.
2. because the scale of matrixicty is too small, a portion of the gaussian primitives will be cropped. So you have to update this code: https://github.com/city-super/Octree-GS/blob/e18dc4f58eaf054798c61c8c986d83257895ae6f/submodules/diff-gaussian-rasterization/cuda_rasterizer/auxiliary.h#L154 In the code, you need to modify the value of "p_view.z" from 0.2 to a much smaller number, such as 0.0001.

**Comment by XiaokangWei** [comment]
Thanks for your reply!
Follow your suggestions,  i have use the street rgbd pointCloud.py and change the 'p_view.z',  but the result still looks not enough good.  During the trainning process, i set the base layer is '8' because of the memory limit, so i don't know this factor whether influence the result. and here ,  my trainning scene is the Block  small of street scene in small city group.

The init_point_cloud result like this:
<img width="891" alt="image" src="https://github.com/city-super/Octree-GS/assets/159465749/be73eaaa-30d2-4a63-a6d7-1218d820b9bc">


According to your suggestions, the rendering results like this:

![00010](https://github.com/city-super/Octree-GS/assets/159465749/bf7bfb71-340f-4d50-adb2-caf25385b938)
![00006](https://github.com/city-super/Octree-GS/assets/159465749/8a33e082-df3e-453e-811a-86b7fc78169c)


It turns out that the places that are far away actually get better results, and the places that are near are mushy.

**Comment by jianglh-WHU** [comment]
Could you give me the render opacity(just replace the color with `torch.ones_like(xyz)`), like ⬇️
```
density = torch.ones_like(xyz)

render_opacity, _ = rasterizer(
    means3D = xyz,
    means2D = screenspace_points,
    shs = None,
    colors_precomp = density,
    opacities = opacity,
    scales = scaling,
    rotations = rot,
    cov3D_precomp = None)
```
It is highly probable that this problem is still being caused by p_view.z, and you need to recompile the diff-gaussian-rasterization package.

**Comment by jianglh-WHU** [comment]
If it goes well, the effect will look like this ⬇️

https://github.com/city-super/Octree-GS/assets/71580859/b204c879-319b-4c53-a8db-57272155bd3f

**Comment by XiaokangWei** [comment]
Thanks for your patient reply again！

Did you only adjust p_view.z to 0.0001? Are there any other adjustments?
and does your dataset also use only street_block_small (which just include vertical and horizon view) ?

I would appreciate it if you could share your init_point3d.py and args files. I want to check my Settings against each other.
