### ISSUE TITLE
martixCity street scene experiments

### ISSUE THREAD

**Issue by XiaokangWei** [city-super/Octree-GS#21]
Thanks for your patient reply！

Did you only adjust p_view.z to 0.0001? Are there any other adjustments?
and does your dataset also use only street_block_small (which just include vertical and horizon view) ?

I would appreciate it if you could share your init_point3d.py and args files. I want to check my Settings against each other.

Thanks!

#16

**Comment by jianglh-WHU** [comment]
Hi, we have discovered that directly increasing the scale overall by a factor of 10 yields better results, primarily due to the learning rate. The config is identical to [train_matrix_city.sh](https://github.com/city-super/Octree-GS/blob/main/train_matrix_city.sh). Here is the [block small init point cloud](https://drive.google.com/file/d/1nST0-N0tTIZo9-VVqGpy311CLWxaYad1/view?usp=drive_link). Additionally, during training, please remember to set `c2w[:3,3]*=10`.
